swagger: "2.0"
info:
  version: 1.0.0
  title: Sample API
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /hello:
    get:
      summary: Returns a hello message
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: Hello, world!
